//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatFlap.CLI {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CatFlap.CLI.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Buffer size in bytes 的本地化字符串。
        /// </summary>
        public static string BufferSizeDescription {
            get {
                return ResourceManager.GetString("BufferSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Listen endpoint, e.g. 0.0.0.0:8080 or [::]:8080 的本地化字符串。
        /// </summary>
        public static string ListenDescription {
            get {
                return ResourceManager.GetString("ListenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Override log level: Verbose, Debug, Information, Warning, Error, Fatal 的本地化字符串。
        /// </summary>
        public static string LogLevelDescription {
            get {
                return ResourceManager.GetString("LogLevelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relay name 的本地化字符串。
        /// </summary>
        public static string NameDescription {
            get {
                return ResourceManager.GetString("NameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable TCP forwarding (enabled by default) 的本地化字符串。
        /// </summary>
        public static string NoTcpDescription {
            get {
                return ResourceManager.GetString("NoTcpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable UDP forwarding (enabled by default) 的本地化字符串。
        /// </summary>
        public static string NoUdpDescription {
            get {
                return ResourceManager.GetString("NoUdpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suppress informational output (Warning level only) 的本地化字符串。
        /// </summary>
        public static string QuietDescription {
            get {
                return ResourceManager.GetString("QuietDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CatFlap - High-performance TCP/UDP relay service
        ///Usage: catflap -l 0.0.0.0:8080 -t 192.168.1.100:80 的本地化字符串。
        /// </summary>
        public static string RootDescription {
            get {
                return ResourceManager.GetString("RootDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target endpoint to forward traffic to, e.g. 192.168.1.100:80 的本地化字符串。
        /// </summary>
        public static string TargetDescription {
            get {
                return ResourceManager.GetString("TargetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Socket timeout in milliseconds 的本地化字符串。
        /// </summary>
        public static string TimeoutDescription {
            get {
                return ResourceManager.GetString("TimeoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable verbose (Debug) logging 的本地化字符串。
        /// </summary>
        public static string VerboseDescription {
            get {
                return ResourceManager.GetString("VerboseDescription", resourceCulture);
            }
        }
    }
}
