// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using Microsoft.AspNetCore.Mvc.ApiExplorer;
using Microsoft.AspNetCore.Mvc.Controllers;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;

namespace CatFlap.Panel.OpenApiTransformer
{
    public sealed class FileUploadOperationTransformer : IOpenApiOperationTransformer
    {
        public Task TransformAsync(OpenApiOperation operation, OpenApiOperationTransformerContext context, CancellationToken ct)
        {
            var apiDescription = context.Description as ApiDescription;
            if (apiDescription?.ActionDescriptor is ControllerActionDescriptor controllerAction)
            {
                // Guard: only apply to POST endpoints (uploads should be POST)
                if (!string.Equals(apiDescription.HttpMethod, "POST", StringComparison.OrdinalIgnoreCase))
                {
                    return Task.CompletedTask;
                }

                // Collect method parameters and exclude CancellationToken (it shouldn't count as an API surface parameter)
                var methodParameters = controllerAction.MethodInfo.GetParameters();
                var nonCancellationParameters = methodParameters
                    .Where(p => p.ParameterType != typeof(CancellationToken))
                    .ToArray();

                var fileParameters = nonCancellationParameters
                    .Where(p => p.ParameterType == typeof(IFormFile))
                    .ToArray();

                // Apply transformation only when the shape is unambiguous: a single file parameter
                if (nonCancellationParameters.Length == 1 && fileParameters.Length == 1)
                {
                    var fileParamName = fileParameters[0].Name ?? "file";

                    // Replace the autogenerated request body with a succinct multipart/form-data model
                    operation.RequestBody = new OpenApiRequestBody
                    {
                        Content = new Dictionary<string, OpenApiMediaType>
                        {
                            ["multipart/form-data"] = new OpenApiMediaType
                            {
                                Schema = new OpenApiSchema
                                {
                                    Type = JsonSchemaType.Object,
                                    Properties = new Dictionary<string, IOpenApiSchema>
                                    {
                                        [fileParamName] = new OpenApiSchema
                                        {
                                            Type = JsonSchemaType.String,
                                            Format = "binary"
                                        }
                                    },
                                    Required = new HashSet<string> { fileParamName }
                                }
                            }
                        }
                    };
                }
            }

            return Task.CompletedTask;
        }
    }
}
